# Libraries for making web requests, writing JSON files, and making dataframes
import requests
import json
import pandas

# Base URL for the API Call
url = "https://gb.hlorenzi.com/api/v1/graphql"
# Replace '226vyt' with the team ID you want to get the board from
# JSON Payload, insomnia will generate the payload, but be sure to paste it in as one line to insomnia
payload = "{team(teamId: \"W2cWZm\"){id, kind, name, tag, iconSrc, flag, gamePreset, ownerIds, updaterIds, createDate, modifyDate, activityDate, wins, draws, losses, baseWins, baseDraws, baseLosses, ratingScheme, ratingMin, ratingAverageByTeam, tiers { name, lowerBound, color }, ratingElo { initial, scalingFactors }, ratingMk8dxMmr { initial, scalingFactors, baselines }, matchCount, playerCount,players { name, ranking, maxRanking, minRanking, wins, losses, playedMatchCount, firstActivityDate, lastActivityDate, initialRating, rating, ratingGain, maxRating, minRating, maxRatingGain, maxRatingLoss, points, maxPointsGain }}}"

# Headers as generated by insomnia
headers = {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "text/plain",
    "Cookie": "_gid=GA1.2.483209941.1763509366; _ga=GA1.1.648776078.1762660449; _ga_CK8MBNP1G1=GS2.1.s1763562124$o6$g1$t1763562245$j60$l0$h0; _gat_gtag_UA_119332275_2=1",
    "origin": "https://gb.hlorenzi.com",
    "priority": "u=1, i",
    "referer": "https://gb.hlorenzi.com/reg/W2cWZm/players",
    "sec-ch-ua": '"Not_A_Brand";v="99", "Chromium";v="142"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Linux"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36"
}

# Main Function
def main():
    # Make the request to the URL, with the payload and headers
    # Generated from insomnia, but moved into main
    response = requests.request("POST", url, data=payload, headers=headers)
    # JSON loads the data as a python dictionary
    response_data = json.loads(response.text)
    # Display the name of the season
    print(response_data["data"]["team"]["name"])
    # Using open, open the response.json file (must exist before running) with write permission
    with open("response.json", "w") as f:
            # Cover the dictionary to a string with json.dumps, with indentation of 4, and write to the file.
        f.write(json.dumps(response_data, indent=4))
    # Get the players data
    players_data = response_data["data"]["team"]["players"]
    # Optional, get the tiers data
    tiers_data = response_data["data"]["team"]["tiers"]

    # Convert the player data into a pandas dataframe
    df_player_rankings = pandas.DataFrame(players_data)

    # Select specific columns to write to a JSON file
    selected_columns = ["name", "rating", "wins", "losses", "playedMatchCount"]

    # Writes selected data to a new JSON file
    df_subset = df_player_rankings[selected_columns]

    df_subset['rating'] = df_subset['rating'].round(0).astype(int)

    df_subset.to_json("player_data.json", orient="records", indent=4)

# Run the main function
if __name__ == "__main__":
    main()
